version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://channl:52KYfVQczDLz0wh1@cluster0.gwuetwk.mongodb.net/
      - JWT_SECRET=7d2c3f9a1e5b8c0d4e6f2a3b5c8d9e0f7a1b2c3d4e5f6a7b8c9d0e1f2a3
      - PORT=5000
      - WHAPI_KEY=DWH5eL1jsooN9GsTIBlaRSRSNGzjEwkK
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s